#!/usr/bin/env bash 

# Verify virtual environment exists - create it if it doesn't
if [ ! -d .venv ]; then
  uv venv .venv
fi
# ACTIVATE VIRTUAL ENVIRONMENT
source .venv/bin/activate >/dev/null 2>&1

# INSTALL DEPENDENCIES
uv pip install -r requirements.txt >/dev/null 2>&1

# RUN SCRAPER
echo "[INFO] Running scraper.."
uv run add_cww_genre.py || echo "[Error] Could not tag tracks.."
echo "[INFO] Scraping done. Exit"
